core/urls.py
from django.urls import path, include
from core.views import deletePost, EditPostView, PostListView, AddPostView,farm_view, register_request, logout_request, login_request, home_view, post_detail, profile_view, mypost_view, UserEditView
from . import views
app_name = 'blog'

urlpatterns = [
    path('farm/', farm_view, name='farm'),
    path('', home_view, name='home'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path('login/', login_request, name='login'),
    path('register/', register_request, name="register"),
    path('logout/', logout_request, name="logout"),
    # path('accounts/profile', include('django.contrib.auth.urls')),
    path('profile/', profile_view, name='profile'),
    path('<pk>/update', UserEditView.as_view(), name="edit_profile"),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('myposts', PostListView.as_view(), name='myposts'),
    path('post_list/', PostListView.as_view(), name='post_list'),
    path('update_post/<int:pk>/', EditPostView.as_view(), name='update_post'),
    path('<id>/delete', deletePost, name="delete_post")

]

django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('api/v1/pokemons/', include('pokeapi.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
class Book(models.Model):
    name = models.CharField(max_length=240, unique=True)
    url = models.CharField(max_length=240)
    image_url = models.CharField(max_length=240)
    img = models.FileField(upload_to='books/', default='BOOK IMAGE')

class Post(models.Model):
    STATUS_CHOICES =(
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=240, unique=True)
    body = models.TextField()
    img = models.FileField(upload_to='posts/')
    slug = models.SlugField(max_length=240, unique_for_date="publish")
    publish = models.DateField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

class Farm(models.Model):
    holding_id = models.IntegerField(unique=True)
    zone = models.CharField(max_length=3)
    brand = models.CharField(max_length=240)
    dob = models.DateField()
    species = models.CharField(max_length=240)
    breed = models.CharField(max_length=240)
    sex = models.CharField(max_length=240)
    age = models.IntegerField()
    colour = models.CharField(max_length=240)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField()

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'comment by {self.name} on {self.post}'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    def __str__(self):
        return f'{self.user.username} Profile'

core/forms.py
from .models import Comment
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
    
    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name', 'email')

core/views.py
import datetime
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.urls import reverse_lazy
from .models import Book, Farm, Post, Comment
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm, NewUserForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm
from .forms import NewUserForm, UserForm

from django.contrib.auth.models import User
from django.views.generic import (UpdateView, CreateView, ListView, DeleteView)
from django.urls import reverse_lazy

# Create your views here.

def displayTime(request):
	now = datetime.datetime.now()
	text = "The time is {}".format(now)
	return HttpResponse(text)

def farm_view(request):
	farm = Farm.objects.all()
	return render(request, 'farm.html', {'farm_data': farm})

def home_view(request):
	post_list = Post.objects.all()
	#comments = Comment.objects.all()
	paginator = Paginator(post_list, 3)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = Paginator.page(paginator.num_pages)

	book_list = Book.objects.all()
	
	User = get_user_model()
	users = User.objects.all()
	return render(request, 'home.html', {'books':book_list, 'page': page, 'posts': posts})

def post_detail(request, year, month, day, post):
	post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
	comments = post.comments.filter(active=True)
	new_comment = None
	if request.method == 'POST':
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.post = post
			comment_form.save()
	else:
		comment_form = CommentForm()
	return render(request, 'post_detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form})
	
@login_required(login_url='login')
def profile_view(request):
	
	return render(request, 'registration/profile.html')


def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration Successful.")
			return redirect("blog:home")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render(request=request, template_name="registration/register.html", context={"register_form": form})


def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("blog:home")
			else:
				messages.error(request, "Invalid username or password")
		else:
			messages.error(request, "Invalid username or password")
	form = AuthenticationForm()
	return render(request=request, template_name="registration/login.html", context={"login_form": form})

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.")
	return redirect("blog:home")


def mypost_view(request):
	myposts = Post.objects.all()

	
	return render(request, "registration/myposts.html", {'myposts': myposts})


class UserEditView(UpdateView):
	model = User
	form_class = UserChangeForm
	template_name = 'registration/editprofile.html'
	success_url = reverse_lazy("blog:profile")
	
#Create a new post view
class AddPostView(CreateView):
    model = Post
    template_name = 'registration/addBlogPost.html'
    fields = '__all__'

    success_url = reverse_lazy("blog:profile")

class PostListView(ListView):
    model = Post
    template_name = "registration/profile.html"

class EditPostView(UpdateView):
    model = Post
    template_name = "registration/editpost.html"
    fields = '__all__'

    success_url = reverse_lazy("blog:profile")

@login_required
def deletePost(request, id):
	post_del = get_object_or_404(Post, id = id)
	post_del.delete()
	messages.error(request, "Post was deleted successfully")
	return redirect('blog:profile')

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Project | {% block title %} {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">    
    {% comment %} <link rel="stylesheet" href="{% static 'bootstrap/bootstrap/css/bootstrap.min.css' %}"> {% endcomment %}
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <style>
        body {
            font-family: 'Montserrat';
            font-size: 19px;
        }
        {% block style %}   
        
        
        
        {% endblock style %}
    </style>
</head>
<body>
    {% include 'navbar.html' %}

    {% if messages %}
    <div class="container">
        <div class="alert alert-primary messages" role="alert" >
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>

    </div>
    {% endif %}


    {% block content %}
        
    {% endblock content %}
    
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</html>

core/templates/farm.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Posts {% endblock title %}

{% block content %}
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Holding ID</th>
                <th scope="col">Zone</th>
                <th scope="col">Brand</th>
                <th scope="col">Date of Birth</th>
                <th scope="col">Species</th>
                <th scope="col">Breed</th>
                <th scope="col">Sex</th>
                <th scope="col">Age</th>
                <th scope="col">Colour</th>
            </tr>
        </thead>
    
        {% for i in farm_data %}
        <tbody>     
            <tr>
                <th scope="row">{{ i.holding_id }}</th>
                <td>{{ i.zone }}</td>
                <td>{{ i.brand }}</td>
                <td>{{ i.dob }}</td>
                <td>{{ i.species }}</td>
                <td>{{ i.breed }}</td>
                <td>{{ i.sex }}</td>
                <td>{{ i.age }}</td>
                <td>{{ i.colour }}</td>
            </tr>
        </tbody>
        {% endfor %} 
    </table>

{% endblock content %}

core/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Posts {% endblock title %}

{% block content %}


    <div class="home-content">
    {% for post in posts %}

    <h1 class="title"> <a class="link" href="{{ post.get_absolute_url }}">{{ post.title }}</a> </h1>

    <p class="paragraph"> {{ post.body|truncatewords:50}} </p>
    <img src="{{ post.img.url }}" alt="" class="post-img">
        {% for comment in comments %}
            {% if comment.post == post.title %}
                <p class="comment">{{ comment.post }}</p>
            {% endif %}
        {% endfor %}
    {% endfor %}
    </div>

    
    {% include 'pagination.html' with page=posts %}
{% endblock content %}

core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- <h3>List of Pokemons</h3>
    {% for i in response %}
    <h4>NAME:</h4>
    <p>{{ i.name }}</p>
    <h4>IMAGE:</h4>
    {% for l in i %}
    {% with img_url='"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png"' %}
    <img src= {{img_url}} />
    {% endwith %}
    {% endfor %}
    <h4>URL:</h4>
    <a href="{{ i.url }}">{{i.url}}</a><br><br>
    {% endfor %}
    {{ response.results }} -->

    <h1>Pokemons</h1>
    {% for i in response %}

    <ul>
        <li>{{ i.name }}</li> 
    </ul>
    {% endfor %}
</body>
</html>

core/templates/navbar.html
{% comment %} <nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
    <ul class="navbar-nav mr-auto"> 
    </ul>
  </div>
  <div class="mx-auto order-0">
    {% comment %} <a class="navbar-brand" href="/" style="font-size:30px">
      <img src="{% static "img/logo.png" %}" width="35" height="35" alt="logo"> Encore
    </a> {% endcomment %
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target=".dual-collapse2">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:home' %}">Home</a>
      </li>
      {% if user.is_authenticated %}
        
        <li class="nav-item">
          <a class="btn btn-outline-primary" href="{% url 'blog:profile' %}">Welcome {{user.username|title}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:login' %}">Login</a>
        </li>
        <li class="nav-item">
           <a class="btn btn-outline-primary" href="{% url 'blog:register' %}">Register</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav> {% endcomment %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
      <a href="{% url 'blog:home' %}" class="navbar-brand">Sims Blog</a>
      <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
          {% if user.is_authenticated  %}
          
          <div class="navbar-nav">
            <a href="{% url 'blog:home' %}" class="nav-item nav-link active">Home</a>
            <a href="{% url 'blog:myposts' %}" class="nav-item nav-link">My Posts</a>
        </div>
        <div class="navbar-nav ms-auto">
            <a class="btn btn-outline-primary" href="{% url 'blog:profile' %}">Profile</a>
            <a class="nav-link" href="{% url 'blog:profile' %}">Welcome {{user.username|title}}</a>
            <a class="nav-link" href="{% url 'blog:logout' %}">Logout</a>
        </div>
        {% else %}

          <div class="navbar-nav">
            <a href="{% url 'blog:home' %}" class="nav-item nav-link active">Home</a>
        </div>
        <div class="navbar-nav ms-auto">
            <a href="{% url 'blog:login' %}" class="nav-item nav-link">Login</a>
            <a href="{% url 'blog:register' %}" class="nav-item nav-link">Register</a>
        </div>

          {% endif %}
          
            
      </div>
  </div>
</nav>

core/templates/pagination.html
<div class="pagination">
    <span class="page-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}" class="prev">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}" class="next">Next</a>
        {% endif %}
    </span>

</div>

core/templates/post_detail.html
{% extends 'base.html' %}

{% block title %} {{ post.title }} {% endblock title %}

{% block content %}

    <h1> {{ post.title }} </h1>
    {% if post.img %}
    <img src="{{ post.img.url }}" alt="" width="600px" height="300px">
    {% endif %}

    <p class="data">
        Published {{ post.publish }} by {{ post.author }}
    </p>

    {{ post.body|linebreaks }}

    {% with comments.count as total_comments %}
    <h2>{{ total_comments }} Comment{{ total_comments|pluralize }}</h2>

    {% endwith %}

    {% for comment in comments %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
    <h2>Your comment has been added</h2>
    {% else %}
    <h2>Add a new comment</h2>
    <form method="post">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <p><input type="submit" value="Add comment"></p>
    </form>
    {% endif %}

{% endblock content %}